echo "=================================================================================================================";
echo "                                                      kkkkkkkk                                                   "
echo "                                                      k::::::k                                                   "
echo "                                                      k::::::k                                                   "
echo "                                                      k::::::k                                                   "
echo "    ssssssssssyyyyyyy           yyyyyyy  ssssssssss    k:::::k    kkkkkkk eeeeeeeeeeee  yyyyyyy           yyyyyyy"
echo "  ss::::::::::sy:::::y         y:::::y ss::::::::::s   k:::::k   k:::::kee::::::::::::ee y:::::y         y:::::y "
echo "ss:::::::::::::sy:::::y       y:::::yss:::::::::::::s  k:::::k  k:::::ke::::::eeeee:::::eey:::::y       y:::::y  "
echo "s::::::ssss:::::sy:::::y     y:::::y s::::::ssss:::::s k:::::k k:::::ke::::::e     e:::::e y:::::y     y:::::y   "
echo " s:::::s  ssssss  y:::::y   y:::::y   s:::::s  ssssss  k::::::k:::::k e:::::::eeeee::::::e  y:::::y   y:::::y    "
echo "   s::::::s        y:::::y y:::::y      s::::::s       k:::::::::::k  e:::::::::::::::::e    y:::::y y:::::y     "
echo "      s::::::s      y:::::y:::::y          s::::::s    k:::::::::::k  e::::::eeeeeeeeeee      y:::::y:::::y      "
echo "ssssss   s:::::s     y:::::::::y     ssssss   s:::::s  k::::::k:::::k e:::::::e                y:::::::::y       "
echo "s:::::ssss::::::s     y:::::::y      s:::::ssss::::::sk::::::k k:::::ke::::::::e                y:::::::y        "
echo "s::::::::::::::s       y:::::y       s::::::::::::::s k::::::k  k:::::ke::::::::eeeeeeee         y:::::y         "
echo " s:::::::::::ss       y:::::y         s:::::::::::ss  k::::::k   k:::::kee:::::::::::::e        y:::::y          "
echo "  sssssssssss        y:::::y           sssssssssss    kkkkkkkk    kkkkkkk eeeeeeeeeeeeee       y:::::y           "
echo "                    y:::::y                                                                   y:::::y            "
echo "                   y:::::y                                                                   y:::::y             "
echo "                  y:::::y              Twitter: https://twitter.com/skyMetaverse            y:::::y              "
echo "                 y:::::y                                                                   y:::::y               "
echo "                yyyyyyy                                                                   yyyyyyy                "
echo "=================================================================================================================";

